name: Check Prettier formatting

on:
  push:
    branches:
      - t34-cicd
      - main
jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies for Core in GenForm-NPM
        run: npm install
        working-directory: GenForm-NPM/Core/

      - name: Check Prettier formatting for Core in GenForm-NPM
        run: npx prettier . --check
        working-directory: GenForm-NPM/Core/
        
      - name: Install dependencies for React in GenForm-NPM
        run: npm install
        working-directory: GenForm-NPM/React/

      - name: Check Prettier formatting for React in GenForm-NPM
        run: npx prettier . --check
        working-directory: GenForm-NPM/React/

      - name: Install dependencies for Vue in GenForm-NPM
        run: npm install
        working-directory: GenForm-NPM/Vue/

      - name: Check Prettier formatting for Vue in GenForm-NPM
        run: npx prettier . --check
        working-directory: GenForm-NPM/Vue/
      
      - name: Install dependencies for Vanilla in GenForm-Tests
        run: npm install
        working-directory: GenForm-Tests/Vanilla/

      - name: Check Prettier formatting for Vanilla in GenForm-Tests
        run: npx prettier . --check
        working-directory: GenForm-Tests/Vanilla/
      
      - name: Install dependencies for React in GenForm-Tests
        run: npm install
        working-directory: GenForm-Tests/React/

      - name: Check Prettier formatting for React in GenForm-Tests
        run: npx prettier . --check
        working-directory: GenForm-Tests/React/
      
      - name: Install dependencies for Vue in GenForm-Tests
        run: npm install
        working-directory: GenForm-Tests/Vue/

      - name: Check Prettier formatting for Vue in GenForm-Tests
        run: npx prettier . --check
        working-directory: GenForm-Tests/Vue/
