name: Node.js Package version checking

on:
  pull_request:
    branches:
      - main

jobs:
  check-version-Core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: check if Core version is already published
        run: |
          if [ -z "$(git diff --name-only -r HEAD^1 HEAD -- GenForm-NPM/Core)" ]; then
            echo "no changes in this package, skipping version check"
            exit 0
          fi
          currentVersion=$(node -p -e "require('./package.json').version")
          distantVersion=$(npm view @genform/core version)
          if [ "$currentVersion" = "$distantVersion" ]; then
            echo "Version $currentVersion already published"
            exit 1
          fi

  check-version-React:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: check if React version is already published
        run: |
          if [ -z "$(git diff --name-only -r HEAD^1 HEAD -- GenForm-NPM/React)" ]; then
            echo "no changes in this package, skipping version check"
            exit 0
          fi
          currentVersion=$(node -p -e "require('./package.json').version")
          distantVersion=$(npm view @genform/react version)
          if [ "$currentVersion" = "$distantVersion" ]; then
            echo "Version $currentVersion already published"
            exit 1
          fi
