name: Node.js Package building & publishing

on:
  push:
    branches:
      - t34-cicd

jobs:
  check-version-Core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: |
          currentVersion=$(node -p -e "require('./package.json').version")
          distantVersion=$(npm view @genform/core version)
          if [ "$currentVersion" = "$distantVersion" ]; then
            echo "Version $currentVersion already published"
            exit 1
          fi
        working-directory: GenForm-NPM/Core

  # check-version-Vue:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 16
  #     - run: |
  #         currentVersion=$(node -p -e "require('./package.json').version")
  #         distantVersion=$(npm view @genform/vue version)
  #         if [ "$currentVersion" = "$distantVersion" ]; then
  #           echo "Version $currentVersion already published"
  #           exit 1
  #         fi
  #   working-directory: GenForm-NPM/Vue

  check-version-React:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: |
          currentVersion=$(node -p -e "require('./package.json').version")
          distantVersion=$(npm view @genform/react version)
          if [ "$currentVersion" = "$distantVersion" ]; then
            echo "Version $currentVersion already published"
            exit 1
          fi
        working-directory: GenForm-NPM/React

  build-publish-Core:
    needs: check-version-Core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Clean Install
        run: npm ci
        working-directory: GenForm-NPM/Core
      - name: Create Minified Version
        run: npm run minify
        working-directory: GenForm-NPM/Core
      - name: Check if it is all good
        run: ls
        working-directory: GenForm-NPM/Core
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  # build&publish-Vue:
  #   need: check-version-Vue
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 16
  #         registry-url: https://registry.npmjs.org/@genform/vue
  #     - run: npm ci
  #    # - run: npm run minify
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  #   working-directory: GenForm-NPM/Vue

  build-publish-React:
    needs: check-version-React
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: GenForm-NPM/React
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/@genform/react
      - run: ls
      # - run: npm run minify
      # - run: npm publish
      #   env:
      #       NODE_AUTH_TOKEN: ${{secrets.npm_token}}
