name: Node.js Package building & publishing

on:
  push:
    branches:
      - t47-cicd

jobs:
  # Check if the version is already published
  check-version-Core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Check if the version is already published
        run: |
          currentVersion=$(node -p -e "require('./package.json').version")
          distantVersion=$(npm view @genform/core version)
          if [ "$currentVersion" = "$distantVersion" ]; then
            echo "Version $currentVersion already published"
            exit 1
          else
            echo "Version $currentVersion not published yet"
          fi
        working-directory: GenForm-NPM/Core

  check-version-React:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Check if the version is already published
        run: |
          currentVersion=$(node -p -e "require('./package.json').version")
          distantVersion=$(npm view @genform/react version)
          if [ "$currentVersion" = "$distantVersion" ]; then
            echo "Version $currentVersion already published"
            exit 1
          else
            echo "Version $currentVersion not published yet"
          fi
        working-directory: GenForm-NPM/React

  # Build and publish the package if the version is not already published
  build-publish-Core:
    needs: check-version-Core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.com/'
      - name: Clean Install
        run: npm ci
        working-directory: GenForm-NPM/Core
      - name: print registry
        run: npm config get registry
        working-directory: GenForm-NPM/Core
      - name: Create Minified Version
        run: npm run minify
        working-directory: GenForm-NPM/Core
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          token: ${{ secrets.NPM_TOKEN }}
        working-directory: GenForm-NPM/Core
      - name: Check logs
        run: cat /home/runner/.npm/_logs/2024-01-02T20_20_31_958Z-debug-0.log

  build-publish-React:
    needs: check-version-React
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.com/'
      - name: Clean Install
        run: npm ci
        working-directory: GenForm-NPM/React
      # - name: Create Minified Version
      #   run: npm run minify
      #   working-directory: GenForm-NPM/React
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          token: ${{ secrets.NPM_TOKEN }}
        working-directory: GenForm-NPM/React
