name: Unit Testing

on:
  push:
    branches:
      - t45-cicd

jobs:
  unit-testing-core:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: npm clean install
        run: npm ci
        working-directory: ./GenForm-NPM/Core/

      - name: npm run tests for core
        run: npm test
        working-directory: ./GenForm-NPM/Core/

  cypress-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: ./GenForm-Tests/React/
          working-directory: ./GenForm-Tests/React/
